[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/actualites/2022/06/16/reunion-des-acteurs-et-actrices-de-leducation-aux-sciences-du-numerique/index.html"
to = "/actualites/2022-06-16-reunion-des-acteurs-et-actrices-de-leducation-aux-sciences-du-numerique/"

[[redirects]]
from = "/fondation-unit/index.html"
to = "/ecoles/fondation-unit/"

